<a href="https://colab.research.google.com/github/moyersda/genbus885-final-moyers_d/blob/main/GenBud855_Final_Moyers_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Project - RUSH sportwear and footwear
## Denver Moyers

You work as a sales analyst for RUSH, a globally renowned sportswear and footwear brand known for its innovative designs and performance-oriented products.

The VP of US Sales has tasked you with analyzing sales data for trends and insights that will help company leadership understand the market and identify opportunities for growth. For example, you may want to look for trends or insights in seasonality, retailers, locations, or sales methods. Take initiative to apply your creativity and curiosity to this data.

In addition, she has asked you to answer the following business questions:

What product category (product) had the highest sales (in dollars) in 2021? How much did it sell?
What state had the highest sales (in dollars) of women's products in 2021? How much was it?
What state had the highest sales (in dollars) of men's products in 2021? How much was it?
What retailer purchased the most units in 2021? In 2020?

In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#Import data via Github
products_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_PRODUCTS_885.csv'
retailer_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_RETAILER_885.csv'
sales_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_SALES_885.csv'

#create dataframes
df_products = pd.read_csv(products_url)
df_retailers = pd.read_csv(retailer_url)
df_sales = pd.read_csv(sales_url)

In [5]:
#Preview Data
df_products.head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [6]:
df_retailers.head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

In [7]:
df_sales.head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet