<a href="https://colab.research.google.com/github/moyersda/genbus885-final-moyers_d/blob/Correct-Data/GenBud855_Final_Moyers_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Final Project - RUSH sportwear and footwear
## Denver Moyers

You work as a sales analyst for RUSH, a globally renowned sportswear and footwear brand known for its innovative designs and performance-oriented products.

The VP of US Sales has tasked you with analyzing sales data for trends and insights that will help company leadership understand the market and identify opportunities for growth. For example, you may want to look for trends or insights in seasonality, retailers, locations, or sales methods. Take initiative to apply your creativity and curiosity to this data.

In addition, she has asked you to answer the following business questions:

What product category (product) had the highest sales (in dollars) in 2021? How much did it sell?
What state had the highest sales (in dollars) of women's products in 2021? How much was it?
What state had the highest sales (in dollars) of men's products in 2021? How much was it?
What retailer purchased the most units in 2021? In 2020?

In [92]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [93]:
#Import data via Github
products_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_PRODUCTS_885.csv'
retailer_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_RETAILER_885.csv'
sales_url = 'https://raw.githubusercontent.com/moyersda/genbus885-final-moyers_d/refs/heads/main/TABLE_SALES_885.csv'

#create dataframes
df_products = pd.read_csv(products_url, sep="|")
df_retailers = pd.read_csv(retailer_url)
df_sales = pd.read_csv(sales_url)

In [94]:
#Preview Data
df_products.head()

   PRODUCT_ID               PRODUCT_NAME
0          20      Men's Street Footwear
1          30    Men's Athletic Footwear
2         120    Women's Street Footwear
3         130  Women's Athletic Footwear
4          40              Men's Apparel

In [95]:
df_retailers.head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

In [96]:
df_sales.head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet

###Clean Data

In [97]:
#Check for Nulls
df_products.isnull().sum()

PRODUCT_ID      0
PRODUCT_NAME    0
dtype: int64

In [98]:
df_retailers.isnull().sum()

RETAILER_ID    0
RETAILER       0
REGION         0
STATE          0
CITY           0
dtype: int64

In [99]:
df_sales.isnull().sum()

ORDER_ID            0
RETAILER_ID         0
INVOICE_DATE        0
MONTH               0
DAY                 0
YEAR                0
PRODUCT_ID          0
PRICE_PER_UNIT      2
UNITS_SOLD          0
OPERATING_MARGIN    0
SALES_METHOD        0
dtype: int64

In [100]:
#Get null values
df_sales[df_sales["UNITS_SOLD"].isnull()]

Empty DataFrame
Columns: [ORDER_ID, RETAILER_ID, INVOICE_DATE, MONTH, DAY, YEAR, PRODUCT_ID, PRICE_PER_UNIT, UNITS_SOLD, OPERATING_MARGIN, SALES_METHOD]
Index: []

In [101]:
#Delete Null Records
df_sales = df_sales.dropna()

In [102]:
#Check Values
df_retailers["STATE"].value_counts()

STATE
Florida           6
New York          5
Texas             5
California        4
Idaho             3
Mississippi       3
Maryland          3
Hawaii            3
Alaska            2
Illinois          2
Massachusetts     2
New Hampshire     2
Vermont           2
Alabama           2
Kentucky          2
North Carolina    2
Ohio              2
Maine             2
South Dakota      2
North Dakota      2
Nebraska          2
Missouri          2
Minnesota         2
Michigan          2
Kansas            2
Iowa              2
Louisiana         2
West Virginia     2
Rhode Island      2
Tennessee         2
Georgia           2
Pennsylvania      2
Delaware          2
Connecticut       2
Arizona           2
Virginia          2
South Carolina    2
Washington        2
Wyoming           2
Montana           2
New Jersey        2
Oklahoma          2
New Mexico        2
Arkansas          2
Indiana           1
Wisconsin         1
Colorado          1
Nevada            1
Oregon            1
Utah              1
Name: count, dtype: int64

In [103]:
df_retailers["REGION"].value_counts()

REGION
Northeast    28
Midwest      24
West         24
South        18
Southeast    16
Name: count, dtype: int64

In [104]:
df_retailers["CITY"].value_counts()

CITY
Charleston        4
Portland          3
Baltimore         3
Jackson           3
Orlando           3
Miami             3
Honolulu          3
Boise             3
New York          3
Houston           3
Des Moines        2
Chicago           2
Burlington        2
Birmingham        2
Louisville        2
Charlotte         2
Anchorage         2
Columbus          2
Boston            2
Manchester        2
Wilmington        2
Hartford          2
Sioux Falls       2
Fargo             2
Omaha             2
St. Louis         2
Minneapolis       2
Detroit           2
Wichita           2
New Orleans       2
Knoxville         2
Dallas            2
Richmond          2
Atlanta           2
Philadelphia      2
Providence        2
Phoenix           2
Los Angeles       2
Seattle           2
Cheyenne          2
Albany            2
Oklahoma City     2
Billings          2
Newark            2
Albuquerque       2
San Francisco     2
Little Rock       2
Indianapolis      1
Milwaukee         1
Denver            1
Las Vegas         1
Salt Lake City    1
Name: count, dtype: int64

In [105]:
#Check Retailer ID
df_sales[df_sales["RETAILER_ID"] == "999999999"]

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
1446,8668,999999999,7/23/2021,7,23,2021,20,60.0,298,0.42,Outlet

In [106]:
#Find most common retailer
df_sales["RETAILER_ID"].value_counts()

#Assign purchase to W00SARLI
df_sales["RETAILER_ID"] = df_sales["RETAILER_ID"].replace("999999999", "W00SARLI")

In [107]:
df_sales["MONTH"].value_counts().sort_index()

MONTH
1     861
2     776
3     802
4     839
5     820
6     729
7     774
8     853
9     824
10    814
11    795
12    759
Name: count, dtype: int64

In [108]:
df_sales["DAY"].value_counts().sort_index()

DAY
1      97
2     192
3     310
4     285
5     337
6     421
7     270
8     305
9     372
10    611
11    424
12    439
13    445
14    293
15    249
16    383
17    687
18    397
19    381
20    330
21    335
22    321
23    396
24    448
25    222
26    222
27    132
28     96
29     91
30     91
31     64
Name: count, dtype: int64

In [109]:
df_sales["YEAR"].value_counts().sort_index()

YEAR
2020    1300
2021    8346
Name: count, dtype: int64

In [110]:
df_sales["PRICE_PER_UNIT"].value_counts().sort_index()

PRICE_PER_UNIT
7.0         4
8.0         1
9.0         7
10.0       16
11.0       11
           ..
101.0       1
103.0       2
105.0       4
110.0       4
99999.0     1
Name: count, Length: 95, dtype: int64

In [111]:
#Clean up 99999.0 value in price per unit with AVG price
avg_price = df_sales["PRICE_PER_UNIT"][df_sales["PRICE_PER_UNIT"] != 99999.0].mean()

# Replace 99999.0 with the average
df_sales["PRICE_PER_UNIT"] = df_sales["PRICE_PER_UNIT"].replace(99999.0, avg_price)

In [112]:
df_sales["UNITS_SOLD"].value_counts()

UNITS_SOLD
225    207
150    202
175    191
300    189
200    174
      ...
16       1
286      1
347      1
352      1
355      1
Name: count, Length: 362, dtype: int64

In [113]:
#Replace *** with AVG Units sold
avg_units = pd.to_numeric(
    df_sales.loc[df_sales["UNITS_SOLD"] != "***", "UNITS_SOLD"]
).mean()

df_sales["UNITS_SOLD"] = df_sales["UNITS_SOLD"].replace("***", avg_units)

In [114]:
df_sales["SALES_METHOD"].value_counts()

SALES_METHOD
Online      4889
Outlet      2999
In-store    1738
Ootlet        20
Name: count, dtype: int64

In [115]:
#Replace Ootlet with Outlet
df_sales["SALES_METHOD"] = df_sales["SALES_METHOD"].replace("Ootlet", "Outlet")

In [116]:
#Check Datatypes
df_products.dtypes

PRODUCT_ID       int64
PRODUCT_NAME    object
dtype: object

In [117]:
df_retailers.dtypes

RETAILER_ID    object
RETAILER       object
REGION         object
STATE          object
CITY           object
dtype: object

In [118]:
df_sales.dtypes

ORDER_ID              int64
RETAILER_ID          object
INVOICE_DATE         object
MONTH                 int64
DAY                   int64
YEAR                  int64
PRODUCT_ID            int64
PRICE_PER_UNIT      float64
UNITS_SOLD           object
OPERATING_MARGIN    float64
SALES_METHOD         object
dtype: object

In [119]:
#Convert Units Sold to Integer
df_sales["UNITS_SOLD"] = df_sales["UNITS_SOLD"].astype(int)

Join Tables Together

In [120]:
#Join Dataframes
df_sales_products = pd.merge(df_sales, df_products, on="PRODUCT_ID", how="left")
df_sales_products_retailers = pd.merge(df_sales_products, df_retailers, on="RETAILER_ID", how="left")

In [121]:
#Check table
df_sales_products_retailers.head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,PRODUCT_NAME,RETAILER,REGION,STATE,CITY
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store,Men's Street Footwear,Amazon,Midwest,Ohio,Columbus
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store,Men's Street Footwear,Amazon,Midwest,Ohio,Columbus
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet,Men's Street Footwear,Amazon,Midwest,Ohio,Columbus
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet,Men's Street Footwear,Amazon,Midwest,Ohio,Columbus
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet,Men's Street Footwear,Amazon,Midwest,Ohio,Columbus

In [122]:
#check for nulls
df_sales_products_retailers.isnull().sum()

ORDER_ID            0
RETAILER_ID         0
INVOICE_DATE        0
MONTH               0
DAY                 0
YEAR                0
PRODUCT_ID          0
PRICE_PER_UNIT      0
UNITS_SOLD          0
OPERATING_MARGIN    0
SALES_METHOD        0
PRODUCT_NAME        0
RETAILER            0
REGION              0
STATE               0
CITY                0
dtype: int64